### ISSUE TITLE
Modifications to OpenCV

### ISSUE THREAD

**Issue by peter254** [latsic/imgalign#1]
Hey,
Thank you for creating this awesome repo!
As I would like to compile with the current version of OpenCV I would like to understand what modifications where necessary - could you elaborate on that? Where there any tutorials that you used?

I also have the issue that, when using the build_opencv.sh within a docker image, the resulting script is different and does not contain the ImgStitch function. Did you compile using a docker image? Which version of emscripten did you use?
I used: ```docker run --rm -v `pwd`:`pwd` -it trzeci/emscripten:sdk-tag-1.38.31-64bit /bin/bash```

**Comment by latsic** [comment]
Hi! Don't know if this helps, but here's a list on how the opencv version here is different from the unchanged opencv Repo. 

1. Custom stitching/matching code, which is not included in opencv, is all located here.
https://github.com/latsic/imgalign/tree/master/opencv_src/modules/features2d/src/img_align

2. Interfaces for the additional code added to this file:
https://github.com/latsic/imgalign/blob/master/opencv_src/modules/features2d/include/opencv2/features2d.

2. Manually moved SIFT/SURF from the opencv_contrib repo over to main opencv repo, made also some namespace adjustments I think.
Look for Sift/Surf files in here: https://github.com/latsic/imgalign/tree/master/opencv_src/modules/features2d/src 

3. Bindings for additional code in opencv so the functions can be called from JS. Commented out stuff I didn't need here as well.
https://github.com/latsic/imgalign/blob/master/opencv_src/modules/js/src/embindgen.py

4. See also following commit to see what modifications in various build files I made. Mostly to get a smaller wasm output file.
https://github.com/latsic/imgalign/commit/d0e702ee54a9b09085c3e7e4cf64c7e798c799b3#diff-91f930bf90f29e1bd8d7c0f1d7d83fa2

and I used EMSDK 1.38.19. Have never used Docker to build this Repo.

Let me know if I can be of more help.
