### ISSUE TITLE
How do I isolate the backend opencv functionality?

### ISSUE THREAD

**Issue by iamvc7** [latsic/imgalign#4]
I have no web dev experience, I would like to use the backend code. Can you please help?

Thanks!

**Comment by latsic** [comment]
There is no backend here, so I guess you asking about the custom OpenCV version used. This would be here:
https://github.com/latsic/imgalign/tree/master/opencv_src

This code is based on OpenCV 3.4 with added custom functionality. You should be able to build this like any other OpenCV 3.4 version with cmake. Once that is done, you can make use of it for example by including it in your own C++ application. 

You can also look here to get some idea about the custom code added to OpenCV.
https://github.com/latsic/imgalign/tree/master/opencv_src/modules/features2d/src/img_align and https://github.com/latsic/imgalign/blob/master/opencv_src/modules/features2d/include/opencv2/features2d.hpp

**Comment by iamvc7** [comment]
Thank you! :)
