### ISSUE TITLE
Multistitcher

### ISSUE THREAD

**Issue by iamvc7** [latsic/imgalign#6]
@latsic, multi-stitcher fails with in some instances when given more 4-5 images, and the output stitches only 3 images. Just wondering, is there anything I need to look into? Thanks!

**Comment by latsic** [comment]
Depends on what kind of pictures you are trying to stitch together. Generally camera position ist important, keep it as fixed as possible, e.g. don't move around between taking pictures. The closer the objects are, you are taking pictures of, the more important this is. Other things to consider are overlapping area of the pictures and feature richness (e.g. stitching pictures of a uniform white wall is rather difficult).
